#!/usr/bin/ash

run_hook() {
	modprobe -a -q dm-crypt >/dev/null 2>&1
	modprobe loop
	modprobe ext4
	[ "${quiet}" = "y" ] && CSQUIET=">/dev/null"

	while [ ! -L '/dev/disk/by-id/ata-Samsung_SSD_840_EVO_250GB_S1DBNSCF805751B-part2' ]; do
		echo 'Waiting for USB'
		sleep 1
	done

	cryptsetup open /dev/disk/by-id/ata-Samsung_SSD_840_EVO_250GB_S1DBNSCF805751B-part2 cryptboot
	mkdir -p /mnt
	mount /dev/mapper/cryptboot /mnt
	cryptsetup open /mnt/key.img lukskey
	cryptsetup --header /mnt/header_ssd.img --key-file=/dev/mapper/lukskey --keyfile-offset=1 --keyfile-size=8192 open /dev/disk/by-id/wwn-0x5002538e40857cc4-part1 ssd
	cryptsetup --header /mnt/header_hdd_2tb.img --key-file=/dev/mapper/lukskey --keyfile-offset=8193 --keyfile-size=8192 open /dev/disk/by-id/wwn-0x50014ee265c186a7-part1 hdd
	cryptsetup --header /mnt/header_hdd_1tb_1.img --key-file=/dev/mapper/lukskey --keyfile-offset=0 --keyfile-size=8192 open /dev/disk/by-id/wwn-0x50014ee20debe6b3-part1 hdd2
	cryptsetup close lukskey
}
