theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "music"
player = "mpd"
max_width=50
buttons = ["play", "next"]

[[block]]
block = "pacman"

[[block]]
block = "net"
device = "enp3s0"
format = "{speed_up;K} {speed_down;K}"
format_alt = "{graph_up}{speed_up;K} {graph_down}{speed_down;K}"
interval = 5

[[block]]
block = "temperature"
collapsed = false
interval = 10

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "nvidia_gpu"
show_memory = false

[[block]]
block = "sound"

[[block]]
block = "uptime"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
