theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "music"
player = "mpd"
max_width=50
buttons = ["play", "next"]

[[block]]
block = "pacman"

[[block]]
block = "net"
device = "enp4s0"
ip = false
speed_up = true
speed_down = true
interval = 5

[[block]]
block = "temperature"
collapsed = false
interval = 10

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "nvidia_gpu"
show_memory = false

[[block]]
block = "sound"

[[block]]
block = "uptime"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
