theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "pacman"

[[block]]
block = "net"
device = "eno1"
ip = false
speed_up = true
speed_down = true
interval = 5

[[block]]
block = "temperature"
collapsed = false
interval = 10

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "uptime"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
